console.log('Call node <file> [<parameter> ...]');
console.log('');
console.log('Files & Parameters for the escrow & payment splitter contract:');
console.log(' - openEscrowSlot.js (no parameters)');
console.log('   opens an escrow slot with the paymentSplittingDefinition defined in the settings, from the contract owner account');
console.log('');
console.log(' - fillEscrowSlot.js <account ID> <slot ID>');
console.log('   fills escrow slot from that account - UoA transfer has to be approved calling approveEscrowContractTokenRetrieval.js before');
console.log('');
console.log(' - settleEscrowSlot.js <account ID> <slot ID>');
console.log('   settles escrow slot from that account - only the account which filled the slot can call it successfully');
console.log('');
console.log(' - getPaymentSplittingDefinition.js <slot ID>');
console.log('');
console.log(' - getEscrowedValue.js <account ID> <slot ID>');
console.log('   get the value escrowed in the slot for account');
console.log('');
console.log(' - isEscrowSlotFilled.js <slot ID>');
console.log('');
console.log('Files & Parameters for the token contract UoA:');
console.log(' - approveEscrowContractTokenRetrieval.js <account ID> <amount of UoA>');
console.log('   allows the escrow & payment splitter contract to transfer the amount from the account to itself');
console.log('');
console.log(' - listTokenBalances.js (no parameters)');
console.log('');
console.log(' - mintToken.js <account ID> <amount of UoA>');
console.log('');
console.log('The account IDs are defined in settings.js');